version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: evanisprettycool
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_admin
      MYSQL_PASSWORD: evanisprettycool

  wordpress:
    depends_on:
      - db
    image: wordpress
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp_admin
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: evanisprettycool
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', true );
        define( 'JETTISON_DEV_MODE', true );
    volumes:
    - .:/var/www/html/wp-content/plugins/jettison

  webpack:
    depends_on:
      - wordpress
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/webpack
    command: yarn dev

volumes:
    db_data: {}